config/routes.rb
Rails.application.routes.draw do
 root 'todos#index'
  resources :todos
end

app/models/todo.rb
class Todo < ActiveRecord::Base

	validates :priority, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

	def index
    @todos = Todo.all
  end

  def create
    @todo = Todo.create(todo_params)
    	respond_to do |format|
    format.html { redirect_to root_path }
    format.js { }  #if in JS will for specific file
  	end
  end

  def destroy
    todo = Todo.find(params[:id])
    todo.destroy
    redirect_to root_path
  end

  private
    def todo_params
      params.require(:todo).permit(:description, :priority)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>



<%= yield %>

</body>
</html>

app/views/todos/create.js.erb
 var html = "<li><%= @todo.description %><br><strong> Priority: </strong> <%= @todo.priority %><br><%= escape_javascript link_to 'DONE', todo_path(@todo), method: 'delete' %></li>";

 $('ul').append(html);

app/views/todos/index.html.erb
<div class = "row"> 
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">TODO List</a>
            </div>
          </div>


           <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#about"> The todo list you always wanted but never had</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>

        <!-- /.container-fluid --> 
    </nav>
</div>

<br>
<br>
<br>
<br>
<div class = "jumbotron">

  <div class = "container">
    <div class = "col-md-4">
  
      <%= form_for Todo.new do |f| %>
       <div class="input-group" class = "form-control" aria-describedby="basic-addon1" >
          <%= f.text_field :description, placeholder:
          "whatta ya need to do?" %>
        </div>

        <div class="input-group">
          <%= f.number_field :priority, placeholder: "priority level" %>
        </div>

       <div class="input-group" class="btn btn-default">
       <button class="btn btn-default"> <%= f.submit %> </button>
        </div>
      <% end %>

      <ul>
      <% @todos.each do |todo| %>
        <li>
          <%= todo.description %><br>
          <strong>Priority: </strong><%= todo.priority %><br>
          <%= link_to "DONE", todo_path(todo), method: 'delete' %>
        </li>
      <% end %>
      </ul>

      <div>
        <h3>  Priority Levels:   </h3>
          <p>  1 = don't worry about it </p>
          <p>  2 =  kinda important </p>
          <p>  3 = important  </p>
          <p>  4 = pretty important </p>
          <p>  5 = GET THIS DONE!! </p>
      </div>
    </div>

  </div>  
</div>